### ISSUE TITLE
Don't add menu item for Show Whitespace extension

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#749] opened 2017-05-08 18:12 UTC
I'm noticing a startup crash in the brackets-show-whitespace extension, where it tries to add a menu item:

```
AppInit.js:92 TypeError: Cannot read property 'addMenuItem' of undefined
    at loadMenuItem (main.js:282)
    at load (main.js:305)
    at _callHandler (AppInit.js:89)
    at _addListener (AppInit.js:124)
    at Object.appReady (AppInit.js:137)
    at Object.<anonymous> (main.js:318)
    at Object.execCb (require.min.js:29)
    at Z.check (require.min.js:18)
    at Z.<anonymous> (require.min.js:23)
    at require.min.js:8
```

The problem is here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/brackets-show-whitespace/main.js#L281-L287

We don't use the menus, so we can just remove this.

**Comment by hkirat** [comment] 2017-05-08 18:59
Hey @humphd 

I would like to work on this.
Can you point out how to turn on the white space indicator? Don't see it as a default right now.

**Comment by humphd** [comment] 2017-05-09 19:05
I just landed patches on Brackets and Thimble that will make this easier, if you update both.

**Comment by hkirat** [comment] 2017-05-09 19:07
Yes tried that in the morning. Couldn't reproduce the error. 
Could you add the steps to reproduce?

**Comment by humphd** [comment] 2017-05-09 19:08
Even without the error, just rip these lines out.  they are useless in our case.

**Comment by hkirat** [comment] 2017-05-09 19:13
Got it.. working on this now

**Comment by hkirat** [comment] 2017-05-12 19:45
Should be good to close. Will modify the commit message from next time to ensure auto closing.

**Closed** 2017-05-12 20:28 UTC
Labels: Assigned to Contributor, Bug
