### ISSUE TITLE
Switch http-server to http-server-gzip

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#696] opened 2017-04-07 15:25 UTC
For testing our `build-browser-compressed` task, we need to have our `http-server` use `gzip` compression.  https://github.com/cvan/http-server-gzip has added it in a forked repo.  Let's switch to this server in our `package.json`.

**Comment by JohnEJames** [comment] 2017-04-07 15:59
I would like to work on this bug!

**Comment by gideonthomas** [comment] 2017-04-07 20:12
go for it @JohnEJames

you need to make a couple of changes:
1. in the `package.json` remove the current `http-server` entry and add `http-server-gzip` instead using a git path (here's how you do that: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)
2. change the `scripts` object in `package.json`:
   - change [this](https://github.com/mozilla/brackets/blob/master/package.json#L70) to `http-server-gzip` instead of `http-server`
   - change [this](https://github.com/mozilla/brackets/blob/master/package.json#L67) to `npm start -- --gzip`
3. test if `npm start` works on `localhost:8000/src/hosted.html` and `npm run production` works on `localhost:8000/dist/hosted.html`

**Comment by gideonthomas** [comment] 2017-04-07 20:13
Actually wait. That won't work. This package will only serve up gzipped files if they have the `.gz` extension attached to them. @humphd none of the generated files have that extension so it won't set the right `content-encoding` header when serving it up. Any suggestions?

**Comment by humphd** [comment] 2017-04-07 22:39
We could fork his server and make it work properly without reading the filenames (e.g., have it honour whatever flag we call the server with, and just always do it regardless of file ext.  It's probably best if we (mozilla) fork it anyway, so we can control it.

**Comment by gideonthomas** [comment] 2017-04-09 06:16
@humphd the problem is that it's not http-server that's the issue. It includes a dependency called `ecstatic` that enforces the `.gz` extension thing.

**Comment by humphd** [comment] 2017-04-09 23:29
Because none of these projects are really maintained anymore, and likely moving to webpack2 is the real solution long term, let's just fork `http-server-gzip` and `ecstatic` and fix this. The problem is here: https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L88.  Let's just not do that!

@gideonthomas are you willing to fork these into `mozilla` so @JohnEJames can send PRs against them both?

**Comment by gideonthomas** [comment] 2017-04-10 04:45
@JohnEJames alright so here's how you can fix this issue:

1. Fork and clone https://github.com/mozilla/http-server.
2. In that project, open up a PR **agains the `gzip` branch** with a change somewhere around https://github.com/mozilla/http-server/blob/master/lib/http-server.js#L57 to check if `this.gzip` is `true`, and if it is, set the `Content-Encoding` header to `gzip`. Here's an example of how you set a header: https://github.com/mozilla/http-server/blob/master/lib/http-server.js#L69. [at] mention me in your PR.
3. Once that PR is merged in the `package.json` file for brackets, point the `http-server` dependency to the gzip branch of the repository you made the PR against. Here's how you point a dependency to a github url: https://docs.npmjs.com/files/package.json#github-urls
4. In the same `package.json` file, to the `production` script here: https://github.com/mozilla/brackets/blob/master/package.json#L67 change it to 
`npm start -- --gzip`.
5. Run `npm run production` and see if you can access brackets on localhost:8000/dist/hosted.html. If you can, your change worked and you can open up a PR here as well.

**Comment by gideonthomas** [comment] 2017-04-11 23:30
Steps 1 and 2 are done. @JohnEJames you can continue with the rest of the steps.

**Comment by JohnEJames** [comment] 2017-04-12 03:03
Hey @gideonthomas, Linked the git like this

"http-server" : "git://github.com/mozilla/http-server.git",

I thought this was the correct method, but I am not entirely sure. I also added your 
"production": "npm start -- --gzip", command.

When I go to the link this is what I get

![5dffdc4022a617e157ff70997a103b7e](https://cloud.githubusercontent.com/assets/10540058/24939396/08cce80c-1f0b-11e7-8737-3c773b75221d.png)

**Comment by gideonthomas** [comment] 2017-04-12 04:59
@JohnEJames, three things:

1. My comment mentions that you need to point it to the gzip branch of that repository. You haven't done that (that's one possible reason why it's failing)
2. I forgot to mention this but you also need to run `npm install` before running `npm run production`
3. Your link is too verbose. Read the documentation I linked you to in my previous comment. You don't need half of the url you're using.

**Closed** 2017-04-13 16:06 UTC
Labels: Assigned to Contributor
